version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=DavitPra
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5436:5436
    volumes:
      - ./api/postgres_data:/var/lib/postgresql/data
