version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=DavitPra
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./api/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
        - MYSQL_DATABASE=my_store
        # el usuario debe de ser root
        - MYSQL_USER=root
        - MYSQL_ROOT_PASSWORD=admin123
        - MYSQL_PORT=3306
    ports:
        - "3306:3306"
    volumes:
        - ./mysql_data:/var/lib/mysql

  # consultor de datos visual
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      # cual es el servicio que vamos a conectar
      PMA_HOST: mysql
    ports:
      - 8080:80
